clang++-14 \
-MD \
prelim_test.cpp \
../src/model_declaration.cpp \
../src/model_composition.cpp \
../src/model_compilation.cpp \
../src/function_tree.cpp \
../src/model_application.cpp \
../src/data_set.cpp \
../src/process_series_data.cpp \
../src/spreadsheet_inputs.cpp \
../src/llvm_jit.cpp \
../src/ole_wrapper.cpp \
../src/run_model.cpp \
../src/lexer.cpp \
../src/ast.cpp \
../src/emulate.cpp \
../src/units.cpp \
../src/ode_solvers.cpp \
../src/file_utils.cpp \
-std=c++14 \
-D_CRT_SECURE_NO_DEPRECATE \
-D_CRT_SECURE_NO_WARNINGS \
-D_CRT_NONSTDC_NO_DEPRECATE \
-D_CRT_NONSTDC_NO_WARNINGS \
-D_SCL_SECURE_NO_DEPRECATE \
-D_SCL_SECURE_NO_WARNINGS \
-DUNICODE \
-D_UNICODE \
-D__STDC_CONSTANT_MACROS \
-D__STDC_FORMAT_MACROS \
-D__STDC_LIMIT_MACROS \
-O2 
