remote_theme: just-the-docs/just-the-docs
logo : "mobius.png"
favicon_ico: "mobius.ico"

nav_external_links:
  - title: Mobius2 on GitHub
    url: https://github.com/NIVANorge/Mobius2/tree/main
    hide_icon: false
    opens_in_new_tab: true